In [22]:
names =['Neda','Masoud','Helen']
print (names)

['Neda', 'Masoud', 'Helen']


In [23]:
import numpy as np

ages = np.array([35,33,37]);
print(ages)
print(type(ages))
print(ages.shape)

[35 33 37]
<class 'numpy.ndarray'>
(3,)


In [24]:
import numpy as np
rnd = np.random.random((1,3))
print(rnd)
max_rnd=np.argmax(rnd)
print(max_rnd)

[[0.92158524 0.44204413 0.21700187]]
0


In [25]:
names[max_rnd]="Sahar"
print(names)

['Sahar', 'Masoud', 'Helen']


In [26]:
ages[max_rnd]=34;
print(ages)

[34 33 37]
